### ISSUE TITLE
Cannot render view

### ISSUE THREAD

**Issue by snelweg** [FreeCAD/FreeCAD-render#115]
It did work one time. Latest Render WB from add-on manager.

```
[Render] Cannot render view 'Sketch@baseGroup@cascoGroup@LuxcoreProject': Mesh topology is empty (file /home/x/.FreeCAD/Mod/Render/renderables.py, line 164 in check_renderables). Skipping...
20:34:49  [Render] Cannot render view 'Sketch006@bobbelGroup@cascoGroup@LuxcoreProject': Mesh topology is empty (file /home/x/.FreeCAD/Mod/Render/renderables.py, line 164 in check_renderables). Skipping...
20:34:49  [Render] Cannot render view 'Sketch009@bergingGroup@cascoGroup@LuxcoreProject': Mesh topology is empty (file /home/x/.FreeCAD/Mod/Render/renderables.py, line 164 in check_renderables). Skipping...
20:34:49  [Render] Cannot render view 'berging@cascoGroup@LuxcoreProject': Mesh topology is empty (file /home/x/.FreeCAD/Mod/Render/renderables.py, line 164 in check_renderables). Skipping...
20:34:49  Running the Python command 'Render' failed:
Traceback (most recent call last):
  File "/home/x/.FreeCAD/Mod/Render/Render.py", line 1031, in Activated
    project.Proxy.render()
  File "/home/x/.FreeCAD/Mod/Render/Render.py", line 576, in render
    img = renderer.render(obj, prefix, external, output, width, height)
  File "/home/x/.FreeCAD/Mod/Render/rendererhandler.py", line 108, in render
    return self.renderer_module.render(project,
  File "/home/x/.FreeCAD/Mod/Render/renderers/Luxcore.py", line 328, in render
    pageresult.read(project.PageResult)
  File "/tmp/.mount_FreeCA2rKUZa/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/tmp/.mount_FreeCA2rKUZa/usr/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)

File contains no section headers.
file: '/tmp/FreeCAD_Doc_e7c87a6a-4d97-4b1b-bdf1-b68145e651d5_764e4c_4889/LuxcoreProjectceylsqgm.lxs', line: 3
'Renderer "sampler"\n'

```

> OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0126.23662 +3142 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 9732f5f35d54bd1546daaffc9c9cff7e2f0e0249
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

[cv-hok.zip](https://github.com/FreeCAD/FreeCAD-render/files/5889640/cv-hok.zip)

**Comment by howetuft** [comment]
You may have used a Luxrender template (*.lxs) while rending with Luxcore. You must use a Luxcore template (Luxcore_*.cfg)...

**Comment by snelweg** [comment]
> You may have used a Luxrender template (*.lxs) while rending with Luxcore. You must use a Luxcore template (Luxcore_*.cfg)...

I feel so stupid.
You are totally right of course.

**Comment by howetuft** [comment]
You're not stupid, it is the program that is error-prone. I should fix it one day.
