### ISSUE TITLE
Material works after a while start raising an error

### ISSUE THREAD

**Issue by mangelozzi** [FreeCAD/FreeCAD-render#200]
I created this material with the `Render` workbench `Create Material`. 
After awhile it started throwing these errors and fails to recompute:

```
20:03:10  Traceback (most recent call last):
  File "/home/michael/.local/share/FreeCAD/Mod/Render/./Render/material.py", line 111, in execute
    super().execute(obj)
  File "/tmp/.mount_FreeCA4se9RQ/usr/Mod/Arch/ArchMaterial.py", line 403, in execute
    p.ViewObject.ShapeColor = c
<class 'AttributeError'>: 'Gui.ViewProviderDocumentObject' object has no attribute 'ShapeColor'
20:03:10  Recompute failed! Please check report view.
```

FreeCAD info:
```
OS: Ubuntu 20.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20)
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: C/Default (C) [ OS: English/South Africa (en_ZA) ]
Installed mods: 
  * fasteners 0.3.50
  * Manipulator 1.4.9
  * Render 2022.2.0
  * sheetmetal 0.2.50
```

**Comment by howetuft** [comment]
Hello,
May I ask you to attach your FreeCAD file please? I'll have a look inside... Thanks in advance!

**Comment by howetuft** [comment]
As I did not receive an answer to my question above, I am closing the issue...
