### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by crawford** [FreeCAD/FreeCAD-render#314]
I'm trying to render a project of mine which used KiCadStepUp to import a PCB from KiCad. I'm seeing the following error in the logs though:

```
OSError: [Errno 36] File name too long: '/home/alex/.cache/FreeCAD/Cache/FreeCAD_Doc_22dc2980-f492-49e1-8317-017aeb331a76_24d602_15017/Project/assembly#Assembly#PCB_assembly#Assembly#PCB#Step_Models_3918#Top_3918#TP1_TestPoint_Loop_D1_80mm_Drill1_0mm_Beaded_cp002_6edd29a3fb34_ln__assembly#Assembly#PCB#Step_Models_3918#Top_3918#TP1_TestPoint_Loop_D1_80mm_Drill1_0mm_Beaded_cp002_6edd29a3fb34_ln_#Part__Feature019_face0.ply'
```

Additionally, the call to the external render proceeds even after this error, which probably shouldn't happen. I'm happy to take a peek at the code and see if I can come up with some solutions, but I'm posting this here in the meantime.

Here's the full log:

<details>

```
22:41:27  [Render][Objstrings] STARTING OBJECTS EXPORT
22:41:27  [Render][Objstrings] 'assembly#Assembly': Exporting
22:41:46  [Render][Objstrings] /!\ OBJECTS EXPORT ERROR /!\
22:41:46  Traceback (most recent call last):
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/project.py", line 840, in _get_objstrings_worker
    objstrings = [future.result() for future in futures]
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/project.py", line 840, in <listcomp>
    objstrings = [future.result() for future in futures]
22:41:46    File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
22:41:46    File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
22:41:46    File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rdrhandler.py", line 348, in get_rendering_string
    return RendererHandler._render_object(self, name, view)
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rdrhandler.py", line 520, in _render_object
    res = [
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rdrhandler.py", line 521, in <listcomp>
    write_mesh(
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rdrhandler.py", line 746, in _call_renderer
    return renderer_method(*args, **kwargs)
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/renderers/Pbrt.py", line 86, in write_mesh
    plyfile = mesh.write_file(
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rendermesh.py", line 431, in write_file
    self._write_plyfile(
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rendermesh.py", line 682, in _write_plyfile
    with open(plyfile, "w", encoding="utf-8", newline="\n") as f:
22:41:46  OSError: [Errno 36] File name too long: '/home/alex/.cache/FreeCAD/Cache/FreeCAD_Doc_22dc2980-f492-49e1-8317-017aeb331a76_24d602_15017/Project/assembly#Assembly#PCB_assembly#Assembly#PCB#Step_Models_3918#Top_3918#TP1_TestPoint_Loop_D1_80mm_Drill1_0mm_Beaded_cp002_6edd29a3fb34_ln__assembly#Assembly#PCB#Step_Models_3918#Top_3918#TP1_TestPoint_Loop_D1_80mm_Drill1_0mm_Beaded_cp002_6edd29a3fb34_ln_#Part__Feature019_face0.ply'
22:41:46  [Render][Objstrings] /!\ EXPORT ERROR /!\
22:41:46  Traceback (most recent call last):
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/rdrexecutor.py", line 152, in run
    res = self.func(*self.args)
22:41:46    File "/home/alex/.local/share/FreeCAD/Mod/Render/./Render/project.py", line 856, in _get_objstrings_worker
    return objstrings
22:41:46  UnboundLocalError: local variable 'objstrings' referenced before assignment
22:41:46  Starting rendering...
```

**Comment by howetuft** [comment]
Hello,

Good point. It's about Assembly: a mesh file is exported for each assembly component (or even for each face if faces have different materials or colors), and the file name is currently built from assembly hierarchy. If this hierarchy is too large, the resulting file name can be too long from OS point of view.
As a fix, we could imagine that, if the file name is longer than a given limit, we generate another name compliant with OS requirements (for instance with `tempfile.mkstemp`).

> the call to the external render proceeds even after this error, which probably shouldn't happen.

It's a matter of taste. That can be handy for many reasons, including debugging. I think the best way should be to control the behavior (blocking/non blocking) via a setting.

**Comment by howetuft** [comment]
Hello,
#316 should fix your issue. Could you please confirm? Many thanks in advance...

**Comment by crawford** [comment]
Hey, thanks! That fixed the issue.
