### ISSUE TITLE
AttributeError: module 'Material' has no attribute 'MaterialManager'

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#317]
Getting error-messages when trying to define a material based on the render-materials (RENDER - Aluminium).

```
22:06:52  Traceback (most recent call last):
22:06:52    File "/opt/freecad/Mod/Arch/ArchMaterial.py", line 653, in chooseMat
22:06:52      self.material = importFCMat.read(self.cards[card])
22:06:52                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:06:52    File "/opt/freecad/Mod/Material/importFCMat.py", line 102, in read
22:06:52      materialManager = Material.MaterialManager()
22:06:52                        ^^^^^^^^^^^^^^^^^^^^^^^^
22:06:52  AttributeError: module 'Material' has no attribute 'MaterialManager'
```
FreeCAD is:
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34728 +2 (Git)
Build type: Release
Branch: Meins
Hash: a77b641c2a83a30d140e0f531ecbe39514988b8e
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.13
  * Assembly4 0.50.4
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.3.1
  * Silk 0.1.5
  * CurvedShapes 1.0.4
  * DynamicData 2.53.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * ExplodedAssembly
  * A2plus 0.4.60n
  * Render 2023.8.18
  * fasteners 0.4.67

```

**Comment by howetuft** [comment]
Hello @berberic2,
Thank you for reporting! It appears to be the same issue that #312, so I will close this one and report my work in #312, with your permission.

**Comment by berberic2** [comment]
I’m not sure if this is the same problem (error message is quite different), but we will see if fixing #312 fixes this too…
