### ISSUE TITLE
Render.view.ViewProviderView not JSON serializable

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#319]
I’m getting python error-messages from render. 

```
PropertyPythonObject::toString(): failed for <class 'Render.view.ViewProviderView'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type FeaturePython is not JSON serializable

```

Problem is introduced by commit [83d4080fe8](https://github.com/FreeCAD/FreeCAD/commit/83d4080fe8) from 2023-09-24
```
App: fixes #10460: App::PropertyPythonObject is not saving data
    
    Since Py3.11 the methods names __setstate__ and __getstate__ conflict with the method names added to the object class.
    Thus rename them to 'loads' and 'dumps'
```
You may take a look at https://github.com/shaise/FreeCAD_FastenersWB/issues/297

**Comment by howetuft** [comment]
Hello,

Thank you for reporting, and for the link to Fasterners' solution. I'm gonna have look and come back to you.

(I think the transition to 0.22 is going to be a long ordeal, many thanks for your help).

**Comment by howetuft** [comment]
Hello,
#321 should fix it, but I can't test on v0.22: would you be so kind to confirm please?

**Comment by berberic2** [comment]
As far as I can tell, it works with 0.22.

**Comment by howetuft** [comment]
Thank you, I close the issue.
