### ISSUE TITLE
Editing Material try error

### ISSUE THREAD

**Issue by prrvchr** [FreeCAD/FreeCAD-render#330]
Hi,

When I try to edit a Material I have this error:

```
16:11:56  Traceback (most recent call last):
16:11:56    File "/home/prrvchr/.local/share/FreeCAD/Mod/Render/./Render/taskpanels.py", line 642, in on_material_type_changed
16:11:56      self._add_field(param, value, images)
16:11:56    File "/home/prrvchr/.local/share/FreeCAD/Mod/Render/./Render/taskpanels.py", line 788, in _add_field
16:11:56      scalar_init=scalar,
16:11:56  UnboundLocalError: local variable 'scalar' referenced before assignment 
```

If we look at the code effectively scalar can be called without been initialized (fallback case)...

```
                if "Texture" in parsedvalue:
                    # Texture
                    option = TexonlyOption.TEXTURE
                    texture, scalar = str2imageid_ext(parsedvalue[1])
                else:
                    # No value (fallback)
                    option = TexonlyOption.NO_VALUE
                    texture = None
                widget = TexonlyPicker(
                    option,
                    teximages,
                    texture,
                    with_scalar=True,
                    scalar_init=scalar,
                    scalar_label=label,
                )
```

Not knowing the default value, I can't help more...

**Comment by howetuft** [comment]
Thank you, I've applied a patch.
